# -*- coding: utf-8 -*-
"""ISL_ver2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKK_pltHCVsC-TYcEwzufFFpAp5-NMIb

# Convolutional Neural Network for Indian Sign Language

## Part 1: Data Loading
"""

# from google.colab import files
# !pip install kaggle

import os
os.environ['KAGGLE_API_TOKEN']='KGAT_6e25a135cbc02cae857e4e183f4c42de'

!kaggle datasets download -d rushilverma07/indian-sign-language-alphabet-dataset
!unzip indian-sign-language-alphabet-dataset -d isl_new_double

DIR="/content/isl_new_double/dataset - Gesture Speech"

from PIL import Image

sizes=set()
count=0

for root,dirs,files in os.walk(DIR): # walks from root to directories.
# so goes from Hindi... -> a, aa, i .... (recursively) and via files in each
  for file in files:
    if file.lower().endswith(".jpg"): # ensures jpg file
      img=Image.open(os.path.join(root,file))
      count+=1
      sizes.add(img.size) # to get all the unique sizes for an image in the dataset


sizes,count

from torchvision import datasets,transforms

dataset=datasets.ImageFolder(DIR)
len_data=len(dataset)
len(dataset)
# transform=transforms.Grayscale(num_output_channels=3)

#  splitting into test and train data
from torch.utils.data import random_split

train_len=int(len_data*0.8) # 80 percent in training dataset
test_len=len_data-train_len

train_len,test_len

# train_dataset,test_datasets=random_split(dataset,[train_len,test_len]) # incorrect cuz same imagefolder so transform applied to both is same
# len(train_dataset),len(test_datasets)

transform_train=transforms.Compose(
    [
    transforms.Resize((128,128)),
    transforms.ToTensor(), # pixels lie between 0 and 1
    transforms.RandomRotation(20),
    transforms.RandomAffine(degrees=10,translate=(0.1,0.1),scale=(0.9,1.1)),
    transforms.ColorJitter(brightness=0.3,saturation=0.3,contrast=0.3),
    transforms.Normalize(mean=[0.5,0.5,0.5],std=[0.5,0.5,0.5]), # pixels lie btw -1 -> 1. [0.5,0.5,0.5] for [R,G,B]
    transforms.RandomErasing(p=0.3,scale=(0.02,0.1))
    ]
    )

transform_test=transforms.Compose(
   [
    transforms.Resize((128,128)),
    transforms.ToTensor(), # pixels lie between 0 and 1
    transforms.Normalize(mean=[0.5,0.5,0.5],std=[0.5,0.5,0.5]) # pixels lie btw -1 -> 1. [0.5,0.5,0.5] for [R,G,B]
    ]
    )

from torch.utils.data import Subset
import torch

train_dataset=datasets.ImageFolder(DIR,transform=transform_train)
test_dataset=datasets.ImageFolder(DIR,transform=transform_test)

# now test and train both have all 48000 images but with diff types of transforms.
# so we select x images for traina nd rest for train

torch.manual_seed(42) # DO NOT FORGET THIS!

idx=torch.randperm(len_data) # list of indices in random order, split it by 80% of dataset length

train_id=idx[:train_len]
test_id=idx[train_len:]

train_data_sub=Subset(train_dataset,train_id) # subset makes a copy of the image in that specific variable
test_data_sub=Subset(test_dataset,test_id)

len(train_data_sub),len(test_data_sub)

print(len(train_data_sub))
print(len(test_data_sub))

print(train_id[:10])
print(test_id[:10])

print(set(train_id.tolist()) & set(test_id.tolist()))

# train_dataset.classes
import os
print(os.listdir(DIR))
print(dataset.classes)
len(dataset.classes)

print(dataset.class_to_idx)

from collections import Counter

counts=Counter(label for img,label in dataset) # to check for an even dstibution for the dataset
print(counts)

img,label=train_data_sub[0]
img.min(),img.max(),img.mean(),label # cuz doing jst img was showing most the pixels as -1 cuz of the black bg.
# This way, its ensured that the tensors arent jst a bunch of -1s

print(f"Image shape: {img.shape}")

import matplotlib.pyplot as plt
plt.imshow(img.permute(1,2,0)) # black and white image cuz the 0-> 1 is converted to -1 -> 1 for better training over a consistent scale
# 1,2,0 cuz imshow expects (height,width,channels) instead of the (channels,height,width) in img.shape()
print(f"{label}: {train_data_sub.dataset.classes[label]}")

image=img*0.5+0.5 # to undo the normalization

plt.imshow(image.permute(1,2,0)) # black and white image cuz the 0-> 1 is converted to -1 -> 1 for better training over a consistent scale
# 1,2,0 cuz imshow expects (height,width,channels) instead of the (channels,height,width) in img.shape()
print(f"{label}: {train_data_sub.dataset.classes[label]}")

torch.manual_seed(42)
fig=plt.figure(figsize=(12,12))
rows,cols=4,4

for i in range(1,1+(rows*cols)):
  idx_rand=torch.randint(0,len(train_data_sub),size=[1]) # returns one tensor (tensor[15]) (The size part expects a tensor as argument)
  idx_rand=idx_rand.item() # returns the actual index eg 15
  img,label=train_data_sub[idx_rand]
  img=img*0.5+0.5
  fig.add_subplot(rows,cols,i)
  plt.imshow(img.permute(1,2,0))
  # plt.title(train_data_sub.dataset.classes[label]) Not this cuz matplotib dsnt contain devanagiri script
  plt.title(label)
  plt.axis(False)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

from torch.utils.data import DataLoader

Batch_size=64

train_dataloader=DataLoader(train_data_sub,Batch_size,shuffle=True)
test_dataloader=DataLoader(test_data_sub,Batch_size)

len(train_dataloader),len(test_dataloader)

batch_img_train,batch_labels_train=next(iter(train_dataloader))

batch_labels_train.shape,batch_img_train.shape,batch_labels_train[:5]
# batch labels-> [number of batches] batch img-> [number of batches,colours,height,width]

"""## Part 2: Model Definition"""

import torch.nn as nn

class ISL_CNN(nn.Module):
  def __init__(self,num_labels):
    super().__init__()
    self.convolution=nn.Sequential(

        # Block 1:
        nn.Conv2d(3,32,3,padding=1), # (3,128,128) -> (32,128,128)
        nn.BatchNorm2d(32),
        nn.ReLU(),
        nn.MaxPool2d(2,2), # this divides img dim by 2 so (32,64,64)

         # Block 2:
        nn.Conv2d(32,64,3,padding=1),  # (32,64,64) -> (64,64,64)
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.MaxPool2d(2,2), # (64,32,32)

         # Block 3:
        nn.Conv2d(64,128,3,padding=1), # (64,32,32) -> (128,32,32) # DO NOT WRITE THAT 1 WITHOUT THE PADDING
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.MaxPool2d(2,2) # (128,16,16)
    )

    self.fully_connected=nn.Sequential(
        nn.Flatten(), # (128,16,16) -> (32768)
        nn.Linear(128*16*16,512), # (512)
        nn.ReLU(),
        nn.Dropout(0.25), # prevents overfitting
        nn.Linear(512,128), # (128)
        nn.ReLU(),
        nn.Linear(128,num_labels) # (nm_labels) which is 40 in this case
    )

  def forward(self,x):
    x=self.convolution(x)
    x=self.fully_connected(x)
    return x

# cnn block has :
# conv
# norm
# relu
# maxpool

# fc block has
# flatten
# linear
# relu
# dropout
# linear

model_0=ISL_CNN(len(dataset.classes)).to(device)
model_0

"""## Part 3: Training Loop"""

cost_func=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(params=model_0.parameters(),lr=0.001,weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=2, factor=0.5)

def accuracy(y_actual,y_pred):
  correct=torch.eq(y_actual,y_pred).sum()
  acc=(correct.item()/len(y_pred))*100
  return acc

torch.manual_seed(42)

epochs=4

for epoch in range(epochs):
  train_loss=0

  # now, go through all batches per epoch
  for batch,(x,y) in enumerate(train_dataloader):
    # batchnum,tensor of all 64 images, tensor of all 64 labels
    model_0.train()

    x=x.to(device)
    y=y.to(device)

    y_pred=model_0(x)

    loss=cost_func(y_pred,y)

    train_loss+=loss.item() # .item() dont add tensors again!!!

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if (batch%400)==0:
      print(f"{(batch*len(x))/len(train_dataloader.dataset)} Completed")

  train_loss/=len(train_dataloader)

  test_loss=0
  test_acc=0

  with torch.inference_mode():
    model_0.eval()

    for X,Y in test_dataloader:

      X=X.to(device)
      Y=Y.to(device)

      test_pred=model_0(X)
      test_loss+=cost_func(test_pred,Y).item()
      test_acc+=accuracy(Y,test_pred.argmax(dim=1))
      # test pred will be [64,40], so u need the max i the 40 waala dim to getthe predicted label

    test_loss/=len(test_dataloader)
    test_acc/=len(test_dataloader)

  scheduler.step(test_loss)


  print(f"Epoch: {epoch} | Train Loss: {train_loss:.4f} | Test Loss: {test_loss:.4f} | Test Acc: {test_acc:.4f}")

"""## Part 4: Testing the Model"""

model_0.eval()
with torch.inference_mode():
    X,Y = next(iter(test_dataloader))
    X,Y = X.to(device),Y.to(device)
    pred=model_0(X).argmax(dim=1)

class_names = test_data_sub.dataset.classes  # gets the actual label names

for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(X[i].cpu().permute(1,2,0)*0.5+0.5)  # undo normalization
    plt.title(f"P:{class_names[pred[i]]} A:{class_names[Y[i]]}")
    plt.axis("off")
plt.show()

# for x,y in enumerate(train_dataloader):
#   print(x,y)

torch.save(model_0.state_dict(),"isl_model_2.pth")
from google.colab import files
files.download("isl_model_2.pth")

import json
with open("class_names.json", "w", encoding="utf-8") as f:
    json.dump(dataset.classes, f, ensure_ascii=False)
files.download("class_names.json")

model_1=ISL_CNN(len(dataset.classes)).to(device)
model_1.load_state_dict(torch.load("isl_model_2.pth"))
model_1.eval()

"""## Part 5: Confusion Matrix"""

!pip install torchmetrics
!pip install mlxtend

from torchmetrics import ConfusionMatrix
from mlxtend.plotting import plot_confusion_matrix

mat=ConfusionMatrix(num_classes=len(class_names),task="multiclass")
mat_tensor=mat(preds=pred.cpu(),target=Y.cpu())

fig,ax=plot_confusion_matrix(conf_mat=mat_tensor.numpy(),figsize=(15,15),class_names=class_names)
plt.show()

all_preds = []
all_labels = []

model_0.eval()
with torch.inference_mode():
    for X, Y in test_dataloader:
        X, Y = X.to(device), Y.to(device)
        preds = model_0(X).argmax(dim=1)
        all_preds.append(preds.cpu())
        all_labels.append(Y.cpu())

all_preds = torch.cat(all_preds)
all_labels = torch.cat(all_labels)

mat = ConfusionMatrix(num_classes=len(class_names), task="multiclass")
mat_tensor = mat(preds=all_preds, target=all_labels)

fig, ax = plot_confusion_matrix(
    conf_mat=mat_tensor.numpy(),
    class_names=class_names,
    figsize=(15, 15)
)